version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PG_DB: server_db
      PG_HOST: db
      PG_USER: postgres
      PG_PASSWORD: S0m3DBP@sSW0rD
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/server
      - /server/node_modules
    command: npm run start:dev
    networks:
      - server-network
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: server_db
      POSTGRES_PASSWORD: S0m3DBP@sSW0rD
    networks:
      - server-network
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
    restart: always
    networks:
      - server-network
networks:
  server-network:
    driver: bridge